apiVersion: apps/v1
kind: Deployment
metadata:
  name: YT-clone-app
  labels:
    app: YT-clone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: YT-clone-app
  template:
    metadata:
      labels:
        app: YT-clone-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: YT-clone-app
        image: rajf5/youtube-clone:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
